import { lazy, Suspense, useMemo, useState } from 'react'
import type { DashboardParticipant } from '../domain/live/liveTypes'
import type { HelpStatus, MessageTargetType } from '../domain/live/livePolicy'
import { matchesDashboardFilters, participantStatusLabel } from '../domain/live/livePolicy'
import { relativeTime } from '../shared/format'

const helpLabel = { INJURY: '다쳤어요', LOST: '길을 모르겠어요', COMPANION: '친구/일행 문제', OTHER: '기타' } as const

const ParticipantMap = lazy(() => import('../components/ParticipantMap').then((module) => ({ default: module.ParticipantMap })))
interface Props { participants: DashboardParticipant[]; busy: boolean; ended: boolean; sendMessage: (type: MessageTargetType, value: string | null, body: string, ids: string[]) => Promise<void>; transitionHelp: (id: string, status: HelpStatus) => Promise<void> }

export function OperatorDashboard({ participants, busy, ended, sendMessage, transitionHelp }: Props) {
  const [query, setQuery] = useState(''); const [grade, setGrade] = useState(''); const [className, setClassName] = useState(''); const [status, setStatus] = useState<DashboardParticipant['status'] | ''>('')
  const [selected, setSelected] = useState<string[]>([]); const [mapOpen, setMapOpen] = useState(true); const [focusedId, setFocusedId] = useState<string | null>(null)
  const [focusVersion, setFocusVersion] = useState(0)
  const [targetType, setTargetType] = useState<MessageTargetType>('ALL'); const [targetValue, setTargetValue] = useState(''); const [body, setBody] = useState('')
  const filtered = useMemo(() => participants.filter((item) => matchesDashboardFilters(item, { query, grade, className, status })), [participants, query, grade, className, status])
  const count = (value: DashboardParticipant['status']) => participants.filter((item) => item.status === value).length
  const submit = async () => { try { await sendMessage(targetType, targetValue.trim() || null, body, selected); setBody('') } catch { /* Parent displays the user-facing error. */ } }
  return <section className="operator-dashboard">
    <div className="dashboard-summary"><Summary label="전체 참가자" value={participants.length}/><Summary label="위치 수신 중" value={count('NORMAL')}/><Summary label="위치 오래됨" value={count('STALE_LOCATION')}/><Summary label="확인 안 됨" value={count('OFFLINE')}/><Summary label="도움 요청" value={count('HELP_REQUEST')} alert={count('HELP_REQUEST') > 0}/></div>
    {ended && <p className="ended-banner">행사가 종료되어 live 새로고침과 업로드가 중단되었습니다. 마지막 수신 상태를 표시합니다.</p>}
    <div className="dashboard-filters"><input aria-label="참가자 검색" placeholder="이름 또는 식별번호" value={query} onChange={(event) => setQuery(event.target.value)}/><input aria-label="학년" placeholder="학년" value={grade} onChange={(event) => setGrade(event.target.value)}/><input aria-label="반" placeholder="반" value={className} onChange={(event) => setClassName(event.target.value)}/><select aria-label="상태" value={status} onChange={(event) => setStatus(event.target.value as typeof status)}><option value="">모든 상태</option>{(['NORMAL','STALE_LOCATION','OFFLINE','HELP_REQUEST'] as const).map((item) => <option key={item} value={item}>{participantStatusLabel[item]}</option>)}</select><button className="map-toggle" onClick={() => setMapOpen((value) => !value)}>{mapOpen ? '목록 우선' : '지도 열기'}</button></div>
    <div className={`dashboard-workspace ${mapOpen ? 'map-open' : ''}`}><div className="dashboard-map"><Suspense fallback={<div className="map-loading">지도 불러오는 중…</div>}><ParticipantMap participants={participants} selectedId={focusedId} focusVersion={focusVersion} select={setFocusedId}/></Suspense></div><div className="participant-list">
      <div className="participant-list-header" aria-hidden="true"><span></span><span>참가자</span><span>상태</span><span>거리</span><span>마지막 위치</span><span>정확도</span><span>조치</span></div>
      {filtered.map((item) => { const canLocate = item.latitude != null && item.longitude != null && item.status !== 'OFFLINE' && item.status !== 'STALE_LOCATION'; return <article key={item.id} className={`participant-row status-${item.status.toLowerCase()} ${focusedId === item.id ? 'selected' : ''}`} onClick={() => setFocusedId(item.id)}><input aria-label={`${item.displayName} 선택`} type="checkbox" checked={selected.includes(item.id)} onClick={(event) => event.stopPropagation()} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))}/><div><strong>{item.displayName}</strong><small>{item.participantIdentifier}{item.grade ? ` · ${item.grade}학년` : ''}{item.className ? ` ${item.className}반` : ''}</small></div><span className="status-chip">{participantStatusLabel[item.status]}</span><button className="locate-participant" disabled={!canLocate} title={canLocate ? '지도에서 참가자 위치 보기' : '현재 확인 가능한 위치가 없습니다'} onClick={(event) => { event.stopPropagation(); if (!canLocate) return; setFocusedId(item.id); setFocusVersion((value) => value + 1); setMapOpen(true) }}>찾아가기</button><dl><div><dt>거리</dt><dd>{(item.distanceM / 1000).toFixed(2)}km</dd></div><div><dt>마지막 위치</dt><dd>{relativeTime(item.lastReceivedAt)}</dd></div><div><dt>정확도</dt><dd>{item.accuracyM == null ? '-' : `${Math.round(item.accuracyM)}m`}</dd></div></dl>{item.helpRequestId && <div className="help-actions"><span>{item.helpType ? helpLabel[item.helpType] : '도움 요청'} · {relativeTime(item.helpCreatedAt)}</span><button disabled={busy || item.helpStatus !== 'OPEN'} onClick={(event) => { event.stopPropagation(); void transitionHelp(item.helpRequestId!, 'ACKNOWLEDGED').catch(() => undefined) }}>확인</button><button disabled={busy || item.helpStatus !== 'ACKNOWLEDGED'} onClick={(event) => { event.stopPropagation(); void transitionHelp(item.helpRequestId!, 'RESOLVED').catch(() => undefined) }}>해결 완료</button></div>}</article> })}
      {filtered.length === 0 && <p className="empty-list">조건에 맞는 참가자가 없습니다.</p>}
    </div></div>
    <details className="announcement-panel"><summary>공지 보내기</summary><div className="announcement-fields"><select disabled={ended} value={targetType} onChange={(event) => setTargetType(event.target.value as MessageTargetType)}><option value="ALL">전체</option><option value="GRADE">학년</option><option value="CLASS">반</option><option value="PARTICIPANT">개별 ID</option><option value="SELECTION">선택한 참가자</option></select>{!['ALL','SELECTION'].includes(targetType) && <input disabled={ended} placeholder="대상 값" value={targetValue} onChange={(event) => setTargetValue(event.target.value)}/>}<textarea disabled={ended} maxLength={1000} placeholder={ended ? '종료된 행사에는 공지를 보낼 수 없습니다' : '운영 공지 (채팅이 아닙니다)'} value={body} onChange={(event) => setBody(event.target.value)}/><button disabled={ended || busy || !body.trim() || (targetType === 'SELECTION' && selected.length === 0)} onClick={() => void submit()}>공지 발송</button></div></details>
  </section>
}
function Summary({ label, value, alert = false }: { label: string; value: number; alert?: boolean }) { return <div className={alert ? 'alert' : ''}><span>{label}</span><strong>{value}</strong></div> }
